version : "2"

services:

    interlock:
        image: ehazlett/interlock:1.1.0
        command: -D run -c /bin/config.toml
        ports:
            - 8080
        volumes:
            - ./config.toml:/bin/config.toml
            - /var/run/docker.sock:/var/run/docker.sock
            - ucp-node-certs:/certs
        restart: always
        network_mode: "bridge"
    nginx:
        image: nginx:latest
        entrypoint: nginx
        command: -g "daemon off;" -c /etc/nginx/nginx.conf
        ports:
          - 80:80
        labels:
          - "interlock.ext.name=nginx"
        depends_on:
          - interlock
        network_mode: "bridge"
        restart: always
volumes:
  ucp-node-certs:
   external: true
