version : "2"

services:

  interlock:

    image: ehazlett/interlock:1.0.0
    command: -D run --discovery etcd://$CONTROLLER_IP:12379 --discovery-tls-ca-cert /kvcerts/ca.pem --discovery-tls-cert /kvcerts/cert.pem --discovery-tls-key /kvcerts/key.pem
    volumes:
        - ucp-node-certs:/certs
        - ucp-node-certs:/kvcerts
        - haproxy:/usr/local/etc/haproxy

  haproxy:

    image: haproxy
    ports:
        - 80:80
        - 443:443
    labels:
        - "interlock.ext.name=haproxy"
    volumes:
        - haproxy:/usr/local/etc/haproxy
    depends_on:
        - interlock

volumes:
  haproxy:
  ucp-node-certs:
   external: true
